export const HEADSHOT_PRESETS = [
  { slug: 'linkedin-professional', title: 'LinkedIn Professional', description: 'Clean and modern corporate profile headshot.', promptAddOn: 'professional LinkedIn-ready portrait, polished and approachable', backgroundStyle: 'soft neutral office backdrop', wardrobeStyle: 'business casual blazer or collared shirt', lightingStyle: 'soft studio lighting', outputRatio: '1:1' },
  { slug: 'executive-portrait', title: 'Executive Portrait', description: 'Premium C-suite style portrait for leadership branding.', promptAddOn: 'executive-level portrait with confident posture and premium look', backgroundStyle: 'luxury office environment', wardrobeStyle: 'tailored suit', lightingStyle: 'dramatic key light with controlled fill', outputRatio: '4:5' },
  { slug: 'startup-founder', title: 'Startup Founder', description: 'Founder-focused portrait with modern startup energy.', promptAddOn: 'founder profile portrait, modern and ambitious', backgroundStyle: 'clean startup workspace', wardrobeStyle: 'smart casual layers', lightingStyle: 'natural window light look', outputRatio: '4:5' },
  { slug: 'real-estate-agent', title: 'Real Estate Agent', description: 'Trust-building agent headshot for listings and bios.', promptAddOn: 'trustworthy real estate agent profile image', backgroundStyle: 'upscale property-inspired background', wardrobeStyle: 'professional business attire', lightingStyle: 'bright welcoming light', outputRatio: '4:5' },
  { slug: 'speaker-coach', title: 'Speaker / Coach', description: 'Personal brand image for coaches and keynote speakers.', promptAddOn: 'confident personal-brand portrait for speaker profile', backgroundStyle: 'subtle stage or gradient backdrop', wardrobeStyle: 'confident modern professional outfit', lightingStyle: 'balanced editorial lighting', outputRatio: '4:5' },
  { slug: 'corporate-team', title: 'Corporate Team Photo', description: 'Consistent style for team directory portraits.', promptAddOn: 'consistent corporate team member portrait', backgroundStyle: 'uniform office background', wardrobeStyle: 'business formal', lightingStyle: 'uniform studio lighting', outputRatio: '1:1' },
  { slug: 'creative-entrepreneur', title: 'Creative Entrepreneur', description: 'Stylish portrait with personality and professionalism.', promptAddOn: 'creative entrepreneur portrait, expressive but professional', backgroundStyle: 'minimal artistic environment', wardrobeStyle: 'stylish contemporary wardrobe', lightingStyle: 'editorial soft contrast lighting', outputRatio: '4:5' },
  { slug: 'medical-professional', title: 'Medical Professional', description: 'Warm, credible portrait for healthcare bios.', promptAddOn: 'medical professional portrait, credible and compassionate', backgroundStyle: 'clean clinical background', wardrobeStyle: 'doctor attire or professional scrubs', lightingStyle: 'bright clean lighting', outputRatio: '4:5' },
  { slug: 'legal-professional', title: 'Legal Professional', description: 'Authoritative attorney profile image.', promptAddOn: 'legal professional portrait, authoritative and trustworthy', backgroundStyle: 'elegant law office background', wardrobeStyle: 'formal legal attire', lightingStyle: 'classic portrait lighting', outputRatio: '4:5' },
  { slug: 'luxury-consultant', title: 'Luxury Consultant', description: 'Premium high-end client-facing portrait.', promptAddOn: 'luxury consultant portrait, refined and premium', backgroundStyle: 'high-end interior backdrop', wardrobeStyle: 'luxury formal styling', lightingStyle: 'cinematic soft directional light', outputRatio: '4:5' },
  { slug: 'tech-founder', title: 'Tech Founder', description: 'Forward-looking portrait for tech leadership.', promptAddOn: 'tech founder portrait, innovative and modern', backgroundStyle: 'subtle tech office aesthetic', wardrobeStyle: 'minimal modern business wear', lightingStyle: 'cool neutral studio light', outputRatio: '4:5' },
  { slug: 'personal-brand-portrait', title: 'Personal Brand Portrait', description: 'Versatile profile image for creators and consultants.', promptAddOn: 'personal brand portrait, polished and authentic', backgroundStyle: 'clean branded gradient background', wardrobeStyle: 'on-brand professional attire', lightingStyle: 'balanced flattering portrait light', outputRatio: '4:5' }
];

export const getHeadshotPresetBySlug = (slug) => HEADSHOT_PRESETS.find((preset) => preset.slug === slug) || HEADSHOT_PRESETS[0];
