export const marketingStudioPresets = [
  { slug: 'product-launch', title: 'Product Launch Campaign', description: 'Launch a new product with awareness and conversion assets.', platforms: ['facebook', 'instagram', 'tiktok', 'youtube', 'email'], promptAddOn: 'Focus on launch urgency, differentiation, and conversion.', outputTypes: ['campaignConcepts', 'socialPosts', 'adCopy', 'imagePrompt', 'videoPrompt'] },
  { slug: 'local-business-promo', title: 'Local Business Promo Campaign', description: 'Drive local foot traffic and nearby awareness.', platforms: ['facebook', 'instagram', 'google-business', 'email'], promptAddOn: 'Emphasize location, trust, and clear call-to-action.', outputTypes: ['campaignConcepts', 'socialPosts', 'adCopy'] },
  { slug: 'webinar-registration', title: 'Webinar Registration Campaign', description: 'Promote webinar signups with value-led messaging.', platforms: ['linkedin', 'facebook', 'email', 'youtube'], promptAddOn: 'Highlight outcomes, expertise, and deadline-based registration.', outputTypes: ['campaignConcepts', 'socialPosts', 'emailPromo', 'adCopy'] },
  { slug: 'lead-magnet', title: 'Lead Magnet Campaign', description: 'Capture leads with downloadable resources.', platforms: ['facebook', 'instagram', 'linkedin', 'email'], promptAddOn: 'Stress immediate value and low-friction conversion.', outputTypes: ['campaignConcepts', 'socialPosts', 'emailPromo', 'adCopy'] },
  { slug: 'black-friday-holiday', title: 'Black Friday / Holiday Campaign', description: 'Seasonal demand generation with urgency offers.', platforms: ['facebook', 'instagram', 'tiktok', 'email'], promptAddOn: 'Use urgency, scarcity, and gifting context where relevant.', outputTypes: ['campaignConcepts', 'socialPosts', 'adCopy', 'imagePrompt', 'videoPrompt'] },
  { slug: 'saas-feature-launch', title: 'SaaS Feature Launch', description: 'Introduce a feature with problem-solution framing.', platforms: ['linkedin', 'twitter', 'youtube', 'email'], promptAddOn: 'Prioritize pain-point relief and proof-oriented messaging.', outputTypes: ['campaignConcepts', 'socialPosts', 'adCopy', 'videoPrompt'] },
  { slug: 'agency-client-acquisition', title: 'Agency Client Acquisition', description: 'Acquire clients for agency services.', platforms: ['linkedin', 'instagram', 'facebook', 'email'], promptAddOn: 'Show authority, outcomes, and clear offer structure.', outputTypes: ['campaignConcepts', 'socialPosts', 'adCopy'] },
  { slug: 'testimonial-proof', title: 'Testimonial / Proof Campaign', description: 'Use social proof to improve trust and conversion.', platforms: ['instagram', 'facebook', 'linkedin', 'email'], promptAddOn: 'Center customer proof and concrete outcomes.', outputTypes: ['campaignConcepts', 'socialPosts', 'adCopy', 'videoPrompt'] },
  { slug: 'before-after', title: 'Before-and-After Campaign', description: 'Show transformational outcomes.', platforms: ['instagram', 'tiktok', 'facebook', 'youtube'], promptAddOn: 'Contrast old state vs new state with measurable benefits.', outputTypes: ['campaignConcepts', 'socialPosts', 'imagePrompt', 'videoPrompt'] },
  { slug: 'influencer-social', title: 'Influencer-Style Social Campaign', description: 'Creator-native hooks and trends for reach.', platforms: ['tiktok', 'instagram', 'youtube'], promptAddOn: 'Use native social style, hooks, and retention beats.', outputTypes: ['campaignConcepts', 'socialPosts', 'videoPrompt'] },
  { slug: 'real-estate-listing', title: 'Real Estate Listing Campaign', description: 'Promote listings with local relevance and urgency.', platforms: ['facebook', 'instagram', 'youtube', 'email'], promptAddOn: 'Highlight neighborhood, lifestyle, and listing urgency.', outputTypes: ['campaignConcepts', 'socialPosts', 'adCopy', 'videoPrompt'] },
  { slug: 'restaurant-local-offer', title: 'Restaurant / Local Offer Campaign', description: 'Promote offers and recurring local visits.', platforms: ['instagram', 'facebook', 'tiktok', 'email'], promptAddOn: 'Emphasize appetizing visuals and visit-driving CTA.', outputTypes: ['campaignConcepts', 'socialPosts', 'adCopy', 'imagePrompt'] },
  { slug: 'ecommerce-product-ad', title: 'Ecommerce Product Ad Campaign', description: 'Drive product sales with direct response creatives.', platforms: ['facebook', 'instagram', 'tiktok', 'youtube'], promptAddOn: 'Focus on offer clarity, objections, and conversion hooks.', outputTypes: ['campaignConcepts', 'socialPosts', 'adCopy', 'imagePrompt', 'videoPrompt'] },
  { slug: 'professional-services-authority', title: 'Professional Services Authority Campaign', description: 'Position expertise and generate qualified leads.', platforms: ['linkedin', 'facebook', 'email', 'youtube'], promptAddOn: 'Lead with authority, credentials, and risk-reduction language.', outputTypes: ['campaignConcepts', 'socialPosts', 'emailPromo', 'adCopy'] },
  { slug: 're-engagement', title: 'Re-Engagement Campaign', description: 'Re-activate dormant leads and customers.', platforms: ['email', 'facebook', 'instagram'], promptAddOn: 'Use win-back messaging, incentives, and familiarity cues.', outputTypes: ['campaignConcepts', 'socialPosts', 'emailPromo', 'adCopy'] }
];
