export const BLOCKED_INPUT_KEYS = new Set([
  "disable_safety_filter",
  "disable_safety_checker",
  "safety_filter",
  "safety_checker",
  "safe_mode",
  "nsfw",
]);

const ratioOptions = ["adaptive", "16:9", "9:16", "1:1", "4:3", "3:4", "21:9"];

export const replicateVideoModels = [
  {
    id: "seedance-2-fast",
    owner: "bytedance",
    name: "seedance-2.0-fast",
    label: "Seedance 2.0 Fast",
    maker: "ByteDance",
    origin: "China",
    priority: "Fast multimodal",
    mode: "multimodal",
    description: "Fast text, first-frame, last-frame, and reference-driven video with optional native audio.",
    docUrl: "https://replicate.com/bytedance/seedance-2.0-fast",
    tags: ["Chinese", "I2V", "FLF", "Reference", "Audio"],
    strengths: ["Fast iteration", "First and last frame", "Up to 9 reference images"],
    inputMap: {
      firstFrame: "image",
      lastFrame: "last_frame_image",
      referenceImages: "reference_images",
      referenceVideos: "reference_videos",
      referenceAudios: "reference_audios",
    },
    mediaLimits: { referenceImages: 9, referenceVideos: 3, referenceAudios: 3 },
    defaults: {
      prompt: "A cinematic slow push-in, soft practical light, natural movement, stable details",
      duration: 5,
      resolution: "720p",
      aspect_ratio: "16:9",
      generate_audio: true,
    },
    controls: [
      { key: "duration", label: "Duration", type: "select", options: [-1, 5, 7, 8, 10, 12, 15], hint: "-1 is intelligent" },
      { key: "resolution", label: "Resolution", type: "select", options: ["480p", "720p"] },
      { key: "aspect_ratio", label: "Aspect", type: "select", options: ratioOptions },
      { key: "generate_audio", label: "Audio", type: "boolean" },
      { key: "seed", label: "Seed", type: "number", min: 0, max: 2147483647 },
    ],
  },
  {
    id: "seedance-2",
    owner: "bytedance",
    name: "seedance-2.0",
    label: "Seedance 2.0",
    maker: "ByteDance",
    origin: "China",
    priority: "Highest Seedance quality",
    mode: "multimodal",
    description: "Higher-quality Seedance 2.0 with first-frame, last-frame, reference media, and audio generation.",
    docUrl: "https://replicate.com/bytedance/seedance-2.0",
    tags: ["Chinese", "I2V", "FLF", "Reference", "Audio"],
    strengths: ["Quality render", "Multimodal references", "Native audio"],
    inputMap: {
      firstFrame: "image",
      lastFrame: "last_frame_image",
      referenceImages: "reference_images",
      referenceVideos: "reference_videos",
      referenceAudios: "reference_audios",
    },
    mediaLimits: { referenceImages: 9, referenceVideos: 3, referenceAudios: 3 },
    defaults: {
      prompt: "A composed cinematic motion shot with natural camera drift and coherent subject movement",
      duration: 5,
      resolution: "720p",
      aspect_ratio: "16:9",
      generate_audio: true,
    },
    controls: [
      { key: "duration", label: "Duration", type: "select", options: [-1, 5, 7, 8, 10, 12, 15], hint: "-1 is intelligent" },
      { key: "resolution", label: "Resolution", type: "select", options: ["480p", "720p", "4K"] },
      { key: "aspect_ratio", label: "Aspect", type: "select", options: ratioOptions },
      { key: "generate_audio", label: "Audio", type: "boolean" },
      { key: "seed", label: "Seed", type: "number", min: 0, max: 2147483647 },
    ],
  },
  {
    id: "wan-27-i2v",
    owner: "wan-video",
    name: "wan-2.7-i2v",
    label: "Wan 2.7 I2V",
    maker: "Alibaba Wan",
    origin: "China",
    priority: "Best FLF control",
    mode: "image-to-video",
    description: "Image-to-video with first and last frame control, clip continuation, and optional audio sync.",
    docUrl: "https://replicate.com/wan-video/wan-2.7-i2v",
    tags: ["Chinese", "I2V", "FLF", "Audio", "Clip"],
    strengths: ["First and last frame", "Clip continuation", "720p or 1080p"],
    inputMap: {
      firstFrame: "first_frame",
      lastFrame: "last_frame",
      firstClip: "first_clip",
      audio: "audio",
    },
    defaults: {
      prompt: "Subtle camera motion, realistic subject movement, cohesive lighting, no warping",
      negative_prompt: "",
      duration: 5,
      resolution: "1080p",
      enable_prompt_expansion: true,
    },
    controls: [
      { key: "negative_prompt", label: "Negative prompt", type: "textarea" },
      { key: "duration", label: "Duration", type: "number", min: 2, max: 15, step: 1 },
      { key: "resolution", label: "Resolution", type: "select", options: ["720p", "1080p"] },
      { key: "enable_prompt_expansion", label: "Prompt expansion", type: "boolean" },
      { key: "seed", label: "Seed", type: "number", min: 0, max: 2147483647 },
    ],
  },
  {
    id: "wan-25-i2v-fast",
    owner: "wan-video",
    name: "wan-2.5-i2v-fast",
    label: "Wan 2.5 I2V Fast",
    maker: "Alibaba Wan",
    origin: "China",
    priority: "Fast Wan with audio",
    mode: "image-to-video",
    description: "Speed-optimized Wan 2.5 image-to-video with optional audio and prompt expansion.",
    docUrl: "https://replicate.com/wan-video/wan-2.5-i2v-fast",
    tags: ["Chinese", "I2V", "Fast", "Audio"],
    strengths: ["Fast Wan", "Audio sync", "480p or 720p"],
    inputMap: { firstFrame: "image", audio: "audio" },
    defaults: {
      prompt: "A polished product-style animation with gentle camera movement and stable texture",
      negative_prompt: "",
      duration: 5,
      resolution: "720p",
      enable_prompt_expansion: true,
    },
    controls: [
      { key: "negative_prompt", label: "Negative prompt", type: "textarea" },
      { key: "duration", label: "Duration", type: "select", options: [5, 8, 10] },
      { key: "resolution", label: "Resolution", type: "select", options: ["480p", "720p"] },
      { key: "enable_prompt_expansion", label: "Prompt expansion", type: "boolean" },
      { key: "seed", label: "Seed", type: "number", min: 0, max: 2147483647 },
    ],
  },
  {
    id: "wan-22-i2v-fast",
    owner: "wan-video",
    name: "wan-2.2-i2v-fast",
    label: "Wan 2.2 I2V Fast",
    maker: "Alibaba Wan + Pruna",
    origin: "China",
    priority: "Lowest cost Wan",
    mode: "image-to-video",
    description: "Very fast Wan 2.2 image-to-video with optional last image and frame interpolation.",
    docUrl: "https://replicate.com/wan-video/wan-2.2-i2v-fast",
    tags: ["Chinese", "I2V", "FLF", "Fast", "Pruna"],
    strengths: ["Low-cost iteration", "Optional last image", "30 FPS interpolation"],
    inputMap: { firstFrame: "image", lastFrame: "last_image" },
    defaults: {
      prompt: "A clean animated reveal with steady motion and a cinematic finish",
      resolution: "480p",
      num_frames: 81,
      frames_per_second: 16,
      interpolate_output: true,
      go_fast: true,
    },
    controls: [
      { key: "resolution", label: "Resolution", type: "select", options: ["480p", "720p"] },
      { key: "num_frames", label: "Frames", type: "select", options: [81, 121] },
      { key: "frames_per_second", label: "FPS", type: "select", options: [16, 24] },
      { key: "interpolate_output", label: "Interpolate", type: "boolean" },
      { key: "go_fast", label: "Fast path", type: "boolean" },
      { key: "seed", label: "Seed", type: "number", min: 0, max: 2147483647 },
    ],
  },
  {
    id: "kling-v16-pro",
    owner: "kwaivgi",
    name: "kling-v1.6-pro",
    label: "Kling v1.6 Pro",
    maker: "Kuaishou Kling",
    origin: "China",
    priority: "Start or end frame",
    mode: "image-to-video",
    version: "d003382e6d0da698b19fe4e51e97fb2a001a47d00332252bc91acc2ab123cd84",
    description: "Kling Pro model with start image, end image, negative prompt, aspect ratio, and duration.",
    docUrl: "https://replicate.com/kwaivgi/kling-v1.6-pro/versions/d003382e6d0da698b19fe4e51e97fb2a001a47d00332252bc91acc2ab123cd84/api",
    tags: ["Chinese", "I2V", "FLF", "Kling"],
    strengths: ["Start or end frame", "Prompt control", "Kling motion"],
    inputMap: { firstFrame: "start_image", lastFrame: "end_image" },
    defaults: {
      prompt: "A precise cinematic transition with smooth camera motion and consistent identity",
      negative_prompt: "",
      aspect_ratio: "16:9",
      cfg_scale: 0.5,
      duration: 5,
    },
    controls: [
      { key: "negative_prompt", label: "Negative prompt", type: "textarea" },
      { key: "aspect_ratio", label: "Aspect", type: "select", options: ["16:9", "9:16", "1:1"] },
      { key: "duration", label: "Duration", type: "select", options: [5, 10] },
      { key: "cfg_scale", label: "Prompt lock", type: "number", min: 0, max: 1, step: 0.1 },
    ],
  },
  {
    id: "minimax-hailuo-23",
    owner: "minimax",
    name: "hailuo-2.3",
    label: "MiniMax Hailuo 2.3",
    maker: "MiniMax",
    origin: "China",
    priority: "Human motion",
    mode: "hybrid",
    description: "High-fidelity text or first-frame video with strong realistic motion and stylization.",
    docUrl: "https://replicate.com/minimax/hailuo-2.3",
    tags: ["Chinese", "I2V", "T2V", "Human motion"],
    strengths: ["Realistic motion", "768p or 1080p", "Text or image"],
    inputMap: { firstFrame: "first_frame_image" },
    defaults: {
      prompt: "Slow handheld camera movement, cinematic lighting, expressive but natural motion",
      duration: 6,
      resolution: "768p",
      prompt_optimizer: true,
    },
    controls: [
      { key: "duration", label: "Duration", type: "select", options: [6, 10] },
      { key: "resolution", label: "Resolution", type: "select", options: ["768p", "1080p"] },
      { key: "prompt_optimizer", label: "Prompt optimizer", type: "boolean" },
    ],
  },
  {
    id: "minimax-hailuo-23-fast",
    owner: "minimax",
    name: "hailuo-2.3-fast",
    label: "MiniMax Hailuo 2.3 Fast",
    maker: "MiniMax",
    origin: "China",
    priority: "Fast human motion",
    mode: "image-to-video",
    description: "Lower-latency Hailuo 2.3 image-to-video for faster iteration.",
    docUrl: "https://replicate.com/minimax/hailuo-2.3-fast",
    tags: ["Chinese", "I2V", "Fast"],
    strengths: ["Fast Hailuo", "Image-only", "Source ratio preserved"],
    inputMap: { firstFrame: "first_frame_image" },
    defaults: {
      prompt: "Subject moves naturally while the camera holds a stable, cinematic composition",
      duration: 6,
      resolution: "768p",
      prompt_optimizer: true,
    },
    controls: [
      { key: "duration", label: "Duration", type: "select", options: [6, 10] },
      { key: "resolution", label: "Resolution", type: "select", options: ["768p", "1080p"] },
      { key: "prompt_optimizer", label: "Prompt optimizer", type: "boolean" },
    ],
  },
  {
    id: "minimax-hailuo-02",
    owner: "minimax",
    name: "hailuo-02",
    label: "MiniMax Hailuo 02",
    maker: "MiniMax",
    origin: "China",
    priority: "First and last frame",
    mode: "hybrid",
    description: "Text or image-to-video with optional first and last frame on supported resolution settings.",
    docUrl: "https://replicate.com/minimax/hailuo-02",
    tags: ["Chinese", "I2V", "FLF", "Physics"],
    strengths: ["Real-world physics", "Optional last frame", "1080p pro mode"],
    inputMap: { firstFrame: "first_frame_image", lastFrame: "last_frame_image" },
    defaults: {
      prompt: "A physically plausible action shot with coherent motion and clean temporal consistency",
      duration: 6,
      resolution: "768p",
      prompt_optimizer: true,
    },
    controls: [
      { key: "duration", label: "Duration", type: "select", options: [6, 10] },
      { key: "resolution", label: "Resolution", type: "select", options: ["512p", "768p", "1080p"] },
      { key: "prompt_optimizer", label: "Prompt optimizer", type: "boolean" },
    ],
  },
  {
    id: "pruna-p-video",
    owner: "prunaai",
    name: "p-video",
    label: "Pruna P-Video",
    maker: "Pruna AI",
    origin: "Global",
    priority: "Fast preview",
    mode: "hybrid",
    description: "Fast all-in-one text, image, and audio-to-video with draft mode and prompt upsampling.",
    docUrl: "https://replicate.com/prunaai/p-video",
    tags: ["I2V", "FLF", "Draft", "Audio"],
    strengths: ["Very fast previews", "Draft mode", "Up to 48 FPS"],
    inputMap: { firstFrame: "image", lastFrame: "last_frame_image", audio: "audio" },
    defaults: {
      prompt: "Fast cinematic motion, crisp subject preservation, clean camera move",
      duration: 5,
      aspect_ratio: "16:9",
      resolution: "720p",
      fps: 24,
      draft: true,
      prompt_upsampling: true,
      save_audio: true,
    },
    controls: [
      { key: "duration", label: "Duration", type: "number", min: 1, max: 20, step: 1 },
      { key: "aspect_ratio", label: "Aspect", type: "select", options: ["16:9", "9:16", "4:3", "3:4", "3:2", "2:3", "1:1"] },
      { key: "resolution", label: "Resolution", type: "select", options: ["720p", "1080p"] },
      { key: "fps", label: "FPS", type: "select", options: [24, 48] },
      { key: "draft", label: "Draft", type: "boolean" },
      { key: "prompt_upsampling", label: "Prompt upsampling", type: "boolean" },
      { key: "save_audio", label: "Save audio", type: "boolean" },
      { key: "seed", label: "Seed", type: "number", min: 0, max: 2147483647 },
    ],
  },
];

export function getReplicateModel(id) {
  return replicateVideoModels.find((model) => model.id === id);
}

export function getAllowedInputKeys(model) {
  const mapped = Object.values(model.inputMap || {}).filter(Boolean);
  const controlKeys = (model.controls || []).map((control) => control.key);
  return new Set(["prompt", ...mapped, ...controlKeys]);
}

export function sanitizeReplicateInput(model, input) {
  const allowed = getAllowedInputKeys(model);
  return Object.fromEntries(
    Object.entries(input || {}).filter(([key, value]) => {
      if (!allowed.has(key) || BLOCKED_INPUT_KEYS.has(key)) return false;
      if (value === "" || value === null || value === undefined) return false;
      if (Array.isArray(value) && value.length === 0) return false;
      return true;
    }),
  );
}
