- generic [ref=e2]:
  - banner [ref=e3]:
    - generic [ref=e4]:
      - generic [ref=e5]:
        - img [ref=e8] [cursor=pointer]
        - navigation [ref=e12]:
          - generic [ref=e13] [cursor=pointer]: Explore
          - generic [ref=e14] [cursor=pointer]: Image
          - generic [ref=e15] [cursor=pointer]: Video
          - generic [ref=e16] [cursor=pointer]: Tools
          - generic [ref=e17] [cursor=pointer]: Storyboard
          - generic [ref=e18] [cursor=pointer]: Edit
          - generic [ref=e19] [cursor=pointer]: Character
          - generic [ref=e20] [cursor=pointer]: Vibe Motion
          - generic [ref=e21] [cursor=pointer]: Cinema Studio
          - generic [ref=e22] [cursor=pointer]: AI Influencer
          - generic [ref=e23] [cursor=pointer]: Apps
          - generic [ref=e24] [cursor=pointer]: Templates
          - generic [ref=e25] [cursor=pointer]: Assist
          - generic [ref=e26] [cursor=pointer]: Community
      - button "Update API Key" [ref=e28]:
        - img [ref=e29]
  - generic [ref=e31]:
    - complementary [ref=e32]:
      - generic [ref=e33]:
        - generic [ref=e34] [cursor=pointer]:
          - button [ref=e35]:
            - img [ref=e36]
          - generic [ref=e41]: Apps
        - generic [ref=e42] [cursor=pointer]:
          - button [ref=e43]:
            - img [ref=e44]
          - generic [ref=e48]: Image
        - generic [ref=e49] [cursor=pointer]:
          - button [ref=e50]:
            - img [ref=e51]
          - generic [ref=e54]: Video
        - generic [ref=e55] [cursor=pointer]:
          - button [ref=e56]:
            - img [ref=e57]
          - generic [ref=e59]: Cinema
        - generic [ref=e60] [cursor=pointer]:
          - button [ref=e61]:
            - img [ref=e62]
          - generic [ref=e65]: Character
        - generic [ref=e66] [cursor=pointer]:
          - button [ref=e67]:
            - img [ref=e68]
          - generic [ref=e71]: AI-VFX
        - generic [ref=e72] [cursor=pointer]:
          - button [ref=e73]:
            - img [ref=e74]
          - generic [ref=e76]: Influencer
        - generic [ref=e77] [cursor=pointer]:
          - button [ref=e78]:
            - img [ref=e79]
          - generic [ref=e86]: Storyboard
        - generic [ref=e87] [cursor=pointer]:
          - button [ref=e88]:
            - img [ref=e89]
          - generic [ref=e91]: Effects
        - generic [ref=e92] [cursor=pointer]:
          - button [ref=e93]:
            - img [ref=e94]
          - generic [ref=e96]: VFX
        - generic [ref=e97] [cursor=pointer]:
          - button [ref=e98]:
            - img [ref=e99]
          - generic [ref=e102]: Edit
        - generic [ref=e103] [cursor=pointer]:
          - button [ref=e104]:
            - img [ref=e105]
          - generic [ref=e110]: Upscale
        - generic [ref=e111] [cursor=pointer]:
          - button [ref=e112]:
            - img [ref=e113]
          - generic [ref=e117]: Audio
        - generic [ref=e118] [cursor=pointer]:
          - button [ref=e119]:
            - img [ref=e120]
          - generic [ref=e124]: Avatar
        - generic [ref=e125] [cursor=pointer]:
          - button [ref=e126]:
            - img [ref=e127]
          - generic [ref=e131]: Training
        - generic [ref=e132] [cursor=pointer]:
          - button [ref=e133]:
            - img [ref=e134]
          - generic [ref=e137]: Video Tools
        - generic [ref=e138] [cursor=pointer]:
          - button [ref=e139]:
            - img [ref=e140]
          - generic [ref=e142]: Render
        - generic [ref=e143] [cursor=pointer]:
          - button [ref=e144]:
            - img [ref=e145]
          - generic [ref=e149]: Video Agent
        - generic [ref=e150] [cursor=pointer]:
          - button [ref=e151]:
            - img [ref=e152]
          - generic [ref=e155]: Director
        - generic [ref=e156] [cursor=pointer]:
          - button [ref=e157]:
            - img [ref=e158]
          - generic [ref=e163]: Timeline
        - generic [ref=e164] [cursor=pointer]:
          - button [ref=e165]:
            - img [ref=e166]
          - generic [ref=e168]: Chat
        - generic [ref=e169] [cursor=pointer]:
          - button [ref=e170]:
            - img [ref=e171]
          - generic [ref=e174]: Commercial
        - generic [ref=e175] [cursor=pointer]:
          - button [ref=e176]:
            - img [ref=e177]
          - generic [ref=e179]: Templates
        - generic [ref=e180] [cursor=pointer]:
          - button [ref=e181]:
            - img [ref=e182]
          - generic [ref=e185]: Explore
        - generic [ref=e186] [cursor=pointer]:
          - button [ref=e187]:
            - img [ref=e188]
          - generic [ref=e191]: Library
        - generic [ref=e192] [cursor=pointer]:
          - button [ref=e193]:
            - img [ref=e194]
          - generic [ref=e199]: Community
        - generic [ref=e200] [cursor=pointer]:
          - button [ref=e201]:
            - img [ref=e202]
          - generic [ref=e206]: Assist
        - generic [ref=e207] [cursor=pointer]:
          - button [ref=e208]:
            - img [ref=e209]
          - generic [ref=e212]: Commits (0)
        - generic [ref=e213] [cursor=pointer]:
          - button [ref=e214]:
            - img [ref=e215]
          - generic [ref=e219]: Remix Go
      - generic [ref=e221] [cursor=pointer]:
        - button [ref=e222]:
          - img [ref=e223]
        - generic [ref=e226]: Settings
    - main [ref=e227]:
      - generic [ref=e229]:
        - generic [ref=e230]:
          - heading "AI-VFX Studio" [level=1] [ref=e231]
          - paragraph [ref=e232]: Apply AI-powered visual effects and transformations to your videos and images with 80+ cinematic effects.
        - generic [ref=e233]:
          - button "⭐ AI Effects" [ref=e234]:
            - generic [ref=e235]: ⭐
            - generic [ref=e236]: AI Effects
          - button "🎬 Motion Controls" [ref=e237]:
            - generic [ref=e238]: 🎬
            - generic [ref=e239]: Motion Controls
          - button "⭐ VFX" [ref=e240]:
            - generic [ref=e241]: ⭐
            - generic [ref=e242]: VFX
        - generic [ref=e243]:
          - generic [ref=e244]:
            - generic [ref=e245]: ⭐
            - heading "AI Effects" [level=2] [ref=e246]
          - generic [ref=e247]:
            - generic [ref=e248] [cursor=pointer]:
              - generic [ref=e249]:
                - img "Kiss Me AI" [ref=e250]
                - img [ref=e253]
              - paragraph [ref=e255]: Kiss Me AI
            - generic [ref=e256] [cursor=pointer]:
              - generic [ref=e257]:
                - img "Kiss" [ref=e258]
                - img [ref=e261]
              - paragraph [ref=e263]: Kiss
            - generic [ref=e264] [cursor=pointer]:
              - generic [ref=e265]:
                - img "Venom" [ref=e266]
                - img [ref=e269]
              - paragraph [ref=e271]: Venom
            - generic [ref=e272] [cursor=pointer]:
              - generic [ref=e273]:
                - img "Hulk" [ref=e274]
                - img [ref=e277]
              - paragraph [ref=e279]: Hulk
            - generic [ref=e280] [cursor=pointer]:
              - generic [ref=e281]:
                - img "Muscle Surge" [ref=e282]
                - img [ref=e285]
              - paragraph [ref=e287]: Muscle Surge
            - generic [ref=e288] [cursor=pointer]:
              - generic [ref=e289]:
                - img "The Tiger Touch" [ref=e290]
                - img [ref=e293]
              - paragraph [ref=e295]: The Tiger Touch
            - generic [ref=e296] [cursor=pointer]:
              - generic [ref=e297]:
                - img "Anything, Robot" [ref=e298]
                - img [ref=e301]
              - paragraph [ref=e303]: Anything, Robot
            - generic [ref=e304] [cursor=pointer]:
              - generic [ref=e305]:
                - img "Warmth of Jesus" [ref=e306]
                - img [ref=e309]
              - paragraph [ref=e311]: Warmth of Jesus
            - generic [ref=e312] [cursor=pointer]:
              - generic [ref=e313]:
                - img "Holy Wings" [ref=e314]
                - img [ref=e317]
              - paragraph [ref=e319]: Holy Wings
            - generic [ref=e320] [cursor=pointer]:
              - generic [ref=e321]:
                - img "Microwave" [ref=e322]
                - img [ref=e325]
              - paragraph [ref=e327]: Microwave
        - generic [ref=e328]:
          - generic [ref=e329]:
            - generic [ref=e330]: 🎬
            - heading "Motion Controls" [level=2] [ref=e331]
          - generic [ref=e332]:
            - generic [ref=e333] [cursor=pointer]:
              - img "360 Orbit" [ref=e335]
              - paragraph [ref=e336]: 360 Orbit
            - generic [ref=e337] [cursor=pointer]:
              - img "Hero Run" [ref=e339]
              - paragraph [ref=e340]: Hero Run
            - generic [ref=e341] [cursor=pointer]:
              - img "Arc Shot" [ref=e343]
              - paragraph [ref=e344]: Arc Shot
            - generic [ref=e345] [cursor=pointer]:
              - img "Matrix Shot" [ref=e347]
              - paragraph [ref=e348]: Matrix Shot
            - generic [ref=e349] [cursor=pointer]:
              - img "Car Chase" [ref=e351]
              - paragraph [ref=e352]: Car Chase
            - generic [ref=e353] [cursor=pointer]:
              - img "Crane Down" [ref=e355]
              - paragraph [ref=e356]: Crane Down
            - generic [ref=e357] [cursor=pointer]:
              - img "Crane Overhead" [ref=e359]
              - paragraph [ref=e360]: Crane Overhead
            - generic [ref=e361] [cursor=pointer]:
              - img "Crane Up" [ref=e363]
              - paragraph [ref=e364]: Crane Up
            - generic [ref=e365] [cursor=pointer]:
              - img "Crash Zoom In" [ref=e367]
              - paragraph [ref=e368]: Crash Zoom In
            - generic [ref=e369] [cursor=pointer]:
              - img "Crash Zoom Out" [ref=e371]
              - paragraph [ref=e372]: Crash Zoom Out
        - generic [ref=e373]:
          - generic [ref=e374]:
            - generic [ref=e375]: ⭐
            - heading "VFX Controls" [level=2] [ref=e376]
          - generic [ref=e377]:
            - generic [ref=e378] [cursor=pointer]:
              - img "Levitate" [ref=e380]
              - paragraph [ref=e381]: Levitate
            - generic [ref=e382] [cursor=pointer]:
              - img "Disintegration" [ref=e384]
              - paragraph [ref=e385]: Disintegration
            - generic [ref=e386] [cursor=pointer]:
              - img "Flying" [ref=e388]
              - paragraph [ref=e389]: Flying
            - generic [ref=e390] [cursor=pointer]:
              - img "Car Explosion" [ref=e392]
              - paragraph [ref=e393]: Car Explosion
            - generic [ref=e394] [cursor=pointer]:
              - img "Tornado" [ref=e396]
              - paragraph [ref=e397]: Tornado
            - generic [ref=e398] [cursor=pointer]:
              - img "Electricity" [ref=e400]
              - paragraph [ref=e401]: Electricity
            - generic [ref=e402] [cursor=pointer]:
              - img "Huge Explosion" [ref=e404]
              - paragraph [ref=e405]: Huge Explosion
            - generic [ref=e406] [cursor=pointer]:
              - img "Decay Time-Lapse" [ref=e408]
              - paragraph [ref=e409]: Decay Time-Lapse
            - generic [ref=e410] [cursor=pointer]:
              - img "Tsunami" [ref=e412]
              - paragraph [ref=e413]: Tsunami
            - generic [ref=e414] [cursor=pointer]:
              - img "Fire" [ref=e416]
              - paragraph [ref=e417]: Fire
            - generic [ref=e418] [cursor=pointer]:
              - img "Robotic Face Reveal" [ref=e420]
              - paragraph [ref=e421]: Robotic Face Reveal
            - generic [ref=e422] [cursor=pointer]:
              - img "Building Explosion" [ref=e424]
              - paragraph [ref=e425]: Building Explosion
        - generic [ref=e427]:
          - button "×" [ref=e428]
          - button "Image URL" [ref=e430]:
            - img [ref=e431]
            - text: Image URL
          - generic [ref=e434]:
            - textbox "Enter your prompt here" [ref=e435]
            - button [ref=e436]:
              - img [ref=e437]
          - generic [ref=e439]:
            - generic [ref=e440]:
              - generic [ref=e441]: Aspect Ratio
              - combobox [ref=e442]:
                - option "16:9"
                - option "9:16" [selected]
                - option "1:1"
            - generic [ref=e443]:
              - generic [ref=e444]: Duration
              - combobox [ref=e445]:
                - option "5s" [selected]
                - option "10s"
            - generic [ref=e446]:
              - generic [ref=e447]: Resolution
              - combobox [ref=e448]:
                - option "480p" [selected]
                - option "720p"
            - generic [ref=e449]:
              - generic [ref=e450]: Quality
              - combobox [ref=e451]:
                - option "Medium" [selected]
                - option "High"