// errorBoundary.js - Error handling wrapper
// Generated by impeccable harden command

export function createErrorBoundary(fn, fallback) {
  return function(...args) {
    try {
      return fn.apply(this, args);
    } catch (error) {
      console.error('Error caught by boundary:', error);
      
      // Show user-friendly message
      if (fallback && typeof fallback === 'function') {
        return fallback(error);
      }
      
      // Default fallback
      return createErrorUI(error);
    }
  };
}

function createErrorUI(error) {
  const container = document.createElement('div');
  container.style.cssText = `
    padding: 2rem;
    text-align: center;
    background: oklch(15% 0 0);
    border: 1px solid oklch(30% 25% 270deg / 0.3);
    border-radius: 0.5rem;
    color: oklch(85% 0 0);
    margin: 1rem;
  `;
  
  container.innerHTML = `
    <div style="font-size: 3rem; margin-bottom: 1rem;">😅</div>
    <h3 style="font-size: 1.25rem; margin-bottom: 0.5rem; color: oklch(90% 0 0);">
      Oops! Something went wrong
    </h3>
    <p style="font-size: 0.875rem; color: oklch(70% 0 0); margin-bottom: 1rem;">
      ${getFriendlyErrorMessage(error)}
    </p>
    <button onclick="location.reload()" style="
      padding: 0.5rem 1.5rem;
      background: oklch(30% 25% 270deg);
      color: white;
      border: none;
      border-radius: 0.375rem;
      cursor: pointer;
      font-size: 0.875rem;
    ">
      Refresh Page
    </button>
  `;
  
  return container;
}

function getFriendlyErrorMessage(error) {
  const message = error.message || '';
  
  if (message.includes('network') || message.includes('fetch')) {
    return "Looks like the internet took a coffee break. Check your connection and try again.";
  }
  
  if (message.includes('API') || message.includes('apiKey')) {
    return "We couldn't reach our AI services. Please check your API configuration.";
  }
  
  if (message.includes('timeout')) {
    return "That took longer than expected. Let's try again.";
  }
  
  return "An unexpected error occurred. Our team has been notified.";
}

// Async error boundary for promises
export function asyncErrorBoundary(promise, fallback) {
  return promise.catch(error => {
    console.error('Async error caught by boundary:', error);
    
    if (fallback && typeof fallback === 'function') {
      return fallback(error);
    }
    
    return {
      error: true,
      message: getFriendlyErrorMessage(error)
    };
  });
}

// Route error boundary
export function routeErrorBoundary(error, route) {
  console.error(`Route error for ${route}:`, error);
  
  const container = document.createElement('div');
  container.style.cssText = `
    padding: 3rem;
    text-align: center;
    color: oklch(85% 0 0);
  `;
  
  container.innerHTML = `
    <h2 style="font-size: 1.5rem; margin-bottom: 1rem;">Unable to load this page</h2>
    <p style="color: oklch(70% 0 0); margin-bottom: 2rem;">
      We couldn't load the ${route} page. Please try again.
    </p>
    <button onclick="window.history.back()" style="
      padding: 0.5rem 1.5rem;
      background: oklch(30% 25% 270deg);
      color: white;
      border: none;
      border-radius: 0.375rem;
      cursor: pointer;
      margin-right: 1rem;
    ">
      Go Back
    </button>
    <button onclick="location.reload()" style="
      padding: 0.5rem 1.5rem;
      background: transparent;
      color: oklch(70% 0 0);
      border: 1px solid oklch(70% 0 0 / 0.3);
      border-radius: 0.375rem;
      cursor: pointer;
    ">
      Refresh
    </button>
  `;
  
  return container;
}

// Initialize global error handler
export function initGlobalErrorHandler() {
  window.addEventListener('error', (event) => {
    console.error('Global error:', event.error);
    // Prevent default browser error handling
    event.preventDefault();
    // Show user-friendly error
    document.body.appendChild(createErrorUI(event.error));
  });
  
  window.addEventListener('unhandledrejection', (event) => {
    console.error('Unhandled promise rejection:', event.reason);
    event.preventDefault();
    document.body.appendChild(createErrorUI(event.reason));
  });
}

// Export for use in other modules
export default {
  createErrorBoundary,
  asyncErrorBoundary,
  routeErrorBoundary,
  initGlobalErrorHandler
};
