// onboarding.js - First-run onboarding flow
// Generated by impeccable onboard command

export function initOnboarding() {
  // Check if user has completed onboarding
  if (localStorage.getItem('higgsfield-onboarding-complete')) {
    return;
  }

  // Create onboarding overlay
  const overlay = document.createElement('div');
  overlay.id = 'onboarding-overlay';
  overlay.style.cssText = `
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: oklch(10% 0 0 / 0.95);
    z-index: 9999;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-family: Inter, sans-serif;
  `;

  // Step 1: Welcome
  const step1 = createStep(1, {
    title: 'Welcome to Higgsfield AI',
    description: 'Your professional video editing studio with AI-powered tools.',
    icon: '🎬',
    tips: [
      'Edit videos with timeline precision',
      'Generate content with AI studios',
      'Collaborate in real-time'
    ]
  });

  // Step 2: Key Features
  const step2 = createStep(2, {
    title: 'Explore AI Studios',
    description: 'Access 30+ specialized studios for every creative need.',
    icon: '🤖',
    tips: [
      'Image Studio: Generate and edit images',
      'Video Studio: Create videos from text',
      'Timeline Editor: Professional editing'
    ]
  });

  // Step 3: Get Started
  const step3 = createStep(3, {
    title: "Let's Get Started",
    description: 'Choose a studio to begin creating.',
    icon: '🚀',
    tips: [
      'Click any studio card to start',
      'Use keyboard shortcuts for speed',
      'Check the timeline for editing'
    ]
  });

  // Add steps to overlay
  overlay.appendChild(step1);
  
  // Navigation buttons
  const nav = document.createElement('div');
  nav.style.cssText = 'position: absolute; bottom: 2rem; right: 2rem; display: flex; gap: 1rem;';
  
  const skipBtn = document.createElement('button');
  skipBtn.textContent = 'Skip Tour';
  skipBtn.className = 'btn-secondary';
  skipBtn.style.cssText = 'padding: 0.5rem 1rem; background: transparent; color: oklch(70% 0 0); border: 1px solid oklch(70% 0 0 / 0.3); border-radius: 0.5rem; cursor: pointer;';
  skipBtn.onclick = () => completeOnboarding(overlay);
  
  const nextBtn = document.createElement('button');
  nextBtn.textContent = 'Next →';
  nextBtn.className = 'btn-primary';
  nextBtn.style.cssText = 'padding: 0.5rem 1.5rem; background: oklch(30% 25% 270deg); color: white; border: none; border-radius: 0.5rem; cursor: pointer;';
  
  let currentStep = 1;
  nextBtn.onclick = () => {
    currentStep++;
    if (currentStep > 3) {
      completeOnboarding(overlay);
      return;
    }
    overlay.innerHTML = '';
    overlay.appendChild(currentStep === 2 ? step2 : step3);
    overlay.appendChild(nav);
  };
  
  nav.appendChild(skipBtn);
  nav.appendChild(nextBtn);
  overlay.appendChild(nav);
  
  document.body.appendChild(overlay);
}

function createStep(stepNum, data) {
  const step = document.createElement('div');
  step.style.cssText = 'text-align: center; max-width: 600px; padding: 2rem;';
  
  step.innerHTML = `
    <div style="font-size: 4rem; margin-bottom: 1rem;">${data.icon}</div>
    <h2 style="font-size: 2rem; margin-bottom: 0.5rem; color: oklch(85% 0 0);">${data.title}</h2>
    <p style="font-size: 1.125rem; margin-bottom: 2rem; color: oklch(70% 0 0);">${data.description}</p>
    <div style="text-align: left; display: inline-block;">
      ${data.tips.map((tip, i) => `
        <div style="padding: 0.5rem 0; color: oklch(80% 0 0);">
          <span style="color: oklch(30% 25% 270deg); margin-right: 0.5rem;">✓</span>
          ${tip}
        </div>
      `).join('')}
    </div>
    <div style="margin-top: 2rem; color: oklch(60% 0 0); font-size: 0.875rem;">
      Step ${stepNum} of 3
    </div>
  `;
  
  return step;
}

function completeOnboarding(overlay) {
  localStorage.setItem('higgsfield-onboarding-complete', 'true');
  overlay.style.transition = 'opacity 300ms ease-out';
  overlay.style.opacity = '0';
  setTimeout(() => overlay.remove(), 300);
}

// Initialize on DOM ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initOnboarding);
} else {
  initOnboarding();
}
